name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: CHECK OUT
      uses: actions/checkout@v3

    - name: BUILD
      run: make build

    - name: TEST
      run: make test
